name: wd
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - asttokens=2.4.1
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.7.4
  - comm=0.2.2
  - debugpy=1.8.2
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgrpc=1.62.2
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.0.1
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.4
  - python-dateutil=2.9.0
  - python_abi=3.12
  - pyzmq=26.0.3
  - re2=2023.09.01
  - readline=8.2
  - setuptools=71.0.4
  - six=1.16.0
  - stack_data=0.6.2
  - tensorboard=2.17.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - pip:
      - cbor==1.0.0
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - coppeliasim-zmqremoteapi-client==2.0.4
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.15.4
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - grpcio==1.65.2
      - gymnasium==0.29.1
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - matplotlib==3.9.1
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.2
      - pillow==10.4.0
      - protobuf==4.25.4
      - pygame==2.6.0
      - pyparsing==3.1.2
      - pytz==2024.1
      - scipy==1.14.0
      - shapely==2.0.5
      - stable-baselines3==2.3.2
      - sympy==1.13.1
      - tensorboard-data-server==0.7.2
      - torch==2.4.0
      - triton==3.0.0
      - tzdata==2024.1
